# Generated by Django 2.2 on 2019-05-31 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points_lkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storypoint', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'points',
                'db_table': 'point',
            },
        ),
        migrations.CreateModel(
            name='Priority_lkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storypriority', models.CharField(max_length=255)),
                ('storyprioritysort', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'priorites',
                'db_table': 'priority',
            },
        ),
        migrations.CreateModel(
            name='Roles_lkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=255)),
                ('rolenamesort', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'roles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprintlabel', models.CharField(max_length=255)),
                ('sprintstartdate', models.DateField(blank=True, null=True)),
                ('sprintenddate', models.DateField(blank=True, null=True)),
                ('sprintcomments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'sprints',
                'db_table': 'sprint',
            },
        ),
        migrations.CreateModel(
            name='Status_lkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storystatus', models.CharField(max_length=255)),
                ('storystatussort', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'satati',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storytitle', models.CharField(max_length=255)),
                ('storydetail', models.TextField(blank=True, null=True)),
                ('storyenterdate', models.DateField()),
                ('storyclosedate', models.DateField(blank=True, null=True)),
                ('assignedsprint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sprintapp.Sprint')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Teammember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('teammemberrole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sprintapp.Roles_lkup')),
            ],
            options={
                'verbose_name_plural': 'teammembers',
                'db_table': 'teammember',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=255)),
                ('taskdetails', models.TextField(blank=True, null=True)),
                ('taskefforttime', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('Teammembermember', models.ManyToManyField(to='sprintapp.Teammember')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sprintapp.Story')),
            ],
            options={
                'verbose_name_plural': 'tasks',
                'db_table': 'task',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='ownerproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stakeholder', to='sprintapp.Teammember'),
        ),
        migrations.AddField(
            model_name='story',
            name='ownersprintteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='technicalowner', to='sprintapp.Teammember'),
        ),
        migrations.AddField(
            model_name='story',
            name='storyeffortpoints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sprintapp.Points_lkup'),
        ),
        migrations.AddField(
            model_name='story',
            name='storypriority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sprintapp.Priority_lkup'),
        ),
        migrations.AddField(
            model_name='story',
            name='storystatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sprintapp.Status_lkup'),
        ),
    ]
